name: write_sdcard_sample
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  cupertino_icons: ^1.0.2
  derry:
  flutter:
    sdk: flutter
  flutter_hooks:
  gap:
  hooks_riverpod:
  logger:
  very_good_analysis:
  utility_widgets:
    git:
      url: https://github.com/HaruhikoMotokawa/utility_widgets.git
      ref: v1.0.0
  file_picker: ^10.1.2
  file: ^7.0.1
  flutter_file_saver: ^0.8.1
  docman: ^1.2.0
  go_router: ^15.0.0
  path_provider: ^2.1.5
dev_dependencies:
  build_runner:
  flutter_lints:
  flutter_test:
    sdk: flutter
  riverpod_generator:
  riverpod_lint:

flutter:
  # assets:
  #   - assets/
  uses-material-design: true

scripts:
  # build_runnerを実行して、同じファイル名があれば古いものを削除する
  build: flutter pub run build_runner build --delete-conflicting-outputs
  # 保存するたびにbuild_runnerを実行して変更を走らせるようになる
  watch: fvm dart run build_runner watch -d
  #  Gradle デーモンプロセスを終了する => ビルドエラーの解消
  gc: pkill -f '.*GradleDaemon.*'
  # テストを実行しカバレッジをHTMLで出力してブラウザで開くスクリプト
  cov: flutter test --coverage && lcov --remove coverage/lcov.info 'lib/**.g.dart' -o coverage/new_lcov.info --ignore-errors unused && genhtml coverage/new_lcov.info -o coverage/html && open coverage/html/index.html
  # very_good testバージョン -> 最初にdart pub global activate very_good_cliで設定が必要
  cov_good: very_good test -- --coverage && lcov --remove coverage/lcov.info 'lib/**.g.dart' -o coverage/lcov.info && genhtml coverage/lcov.info -o coverage/html && open coverage/html/index.html
  # flutterのパッケージとパッケージのキャッシュを削除した上で、再度パッケージを取得する
  reset_flutter: flutter clean && flutter pub cache repair && flutter pub get --no-example
